# Generated by Django 4.0.4 on 2022-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_watchamovie_uuid_remove_watchauser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchauser',
            name='user_email',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
